import { MetadataRoute } from 'next';
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: ['/', '/wp-content/uploads/'],
        disallow: [
          '/api/',
          '/wp-admin/',
          '/wp-login.php',
          '/wp-json/',
          '/author/',
          '/nota/',
          '/page/',
          '/*?cat=',
          '/*?paged=',
          '/*?p=',
          '/*?s=',
          '/feed/',
          '/*/feed',
          '/*/feed/',
          '/_next/',
          '/wp-content/plugins/',
          '/wp-content/themes/',
          '/index.php',
          '/opengraph-image',
          '/*?fbclid=',
          '/*?amp=',
          '/inicio/',
          '/blog-style-listing-example/',
          '/*?utm_source=',
          '/*?utm_medium=',
          '/*?utm_campaign=',
          '/2019/',
          '/2020/',
          '/2021/',
          '/2022/',
          '/2023/',
          '/news/ywnv',
          '/content/ywnv',
          '/goods/ywnv',
          '/shop/ywnv',
          '/amazon/ywnv',
          '/google/ywnv',
          '/yahoo/ywnv',
          '/blog/ywnv',
          '/about/ywnv',
          '/item/ywnv',
                    '/author/',
          '/tag/',
        ],
      },
      // Permitir explícitamente a bots de IA (mejor visibilidad en LLMs/AI Overview)
      { userAgent: 'GPTBot',           allow: '/' },
      { userAgent: 'Google-Extended',  allow: '/' },
      { userAgent: 'PerplexityBot',    allow: '/' },
      { userAgent: 'ClaudeBot',        allow: '/' },
      { userAgent: 'anthropic-ai',     allow: '/' },
      { userAgent: 'CCBot',            allow: '/' },
      // Googlebot-News: sección explícita — sin esto hereda las reglas de * que incluyen
      // Disallow: /feed/ y pueden crear ambigüedad. Google News requiere acceso libre a artículos.
      { userAgent: 'Googlebot-News',   allow: '/' },
      // Image bots: explícitos
      { userAgent: 'Googlebot-Image',  allow: ['/', '/wp-content/uploads/'] },
      { userAgent: 'Bingbot-Image',    allow: ['/', '/wp-content/uploads/'] },
    ],
    sitemap: [
      'https://acontecer.co.cr/sitemap.xml',
      'https://acontecer.co.cr/news-sitemap.xml',
      'https://acontecer.co.cr/image-sitemap.xml',
    ],
    host: 'https://acontecer.co.cr',
  };
}
