/**
 * lib/gobierno.ts — Directorio del Poder Ejecutivo de Costa Rica 2026-2030.
 * Fuente: nombramientos oficiales. Centraliza los datos para el directorio
 * (/gobierno) y los perfiles individuales (/gobierno/[slug]).
 *
 * ⚠️ Un medio no puede tener funcionarios equivocados: el `cargo` proviene de
 * los nombramientos oficiales. Los campos `foto`, `fotoCredito` y `bio` son
 * OPCIONALES y solo deben llenarse con información verificada.
 */

export type Grupo = 'presidencia' | 'ministro' | 'presidencia-ejecutiva';

export interface Funcionario {
  nombre: string;
  cargo: string;          // título corto (tarjetas)
  institucion?: string;   // nombre completo del ministerio/institución (perfil)
  grupo: Grupo;
  foto?: string;          // URL de la foto (opcional)
  fotoCredito?: string;   // crédito: de dónde se tomó la foto (opcional)
  fuenteUrl?: string;     // fuente del currículo / perfil oficial
  fuenteNombre?: string;  // nombre visible de la fuente
  bio?: string;           // reseña / currículo verificado (opcional)
  aliases?: string[];     // slugs históricos o variantes del nombre
}

export const ACCENT: Record<Grupo, string> = {
  'presidencia': '#0000A2',
  'ministro': '#0a73ce',
  'presidencia-ejecutiva': '#0e9f6e',
};

export const GRUPO_LABEL: Record<Grupo, string> = {
  'presidencia': 'Presidencia de la República',
  'ministro': 'Gabinete · Ministerio',
  'presidencia-ejecutiva': 'Presidencia ejecutiva',
};

export function slugify(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase().trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export function funcionarioSlug(f: Pick<Funcionario, 'nombre'>): string {
  return slugify(f.nombre);
}

export const PRESIDENCIA: Funcionario[] = [
  { nombre: 'Laura Fernández Delgado', cargo: 'Presidenta de la República', institucion: 'Presidencia de la República', grupo: 'presidencia' },
  { nombre: 'Francisco Gamboa Soto', cargo: 'Primer vicepresidente', institucion: 'Vicepresidencia de la República', grupo: 'presidencia' },
  { nombre: 'Douglas Soto Campos', cargo: 'Segundo vicepresidente', institucion: 'Vicepresidencia de la República', grupo: 'presidencia' },
];

export const MINISTROS: Funcionario[] = [
  { nombre: "Rodrigo Chaves Robles", cargo: "Presidencia y Hacienda", institucion: "Ministerio de la Presidencia y Ministerio de Hacienda", grupo: 'ministro', foto: "/gobierno/fotos/rodrigo-chaves-robles.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-la-presidencia-y-ministerio-de-hacienda", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es economista y político costarricense. Fue Presidente de la República de Costa Rica entre 2022 y 2026. En mayo de 2026, fue nombrado por la Presidente Laura Fernández Delgado como Ministro de la Presidencia y Ministro de Hacienda para el período 2026-2030.\nCon una trayectoria en organismos internacionales y en la gestión pública, ha liderado iniciativas enfocadas en el fortalecimiento de las finanzas públicas, la modernización del Estado y la ejecución de proyectos estratégicos para el desarrollo del país. Desde sus cargos actuales, coordina la articulación política y económica del Gobierno, impulsando políticas orientadas a la eficiencia institucional, la inversión y el crecimiento de Costa Rica." },
  { nombre: "Manuel Tovar Rivera", cargo: "Relaciones Exteriores y Culto", institucion: "Ministerio de Relaciones Exteriores y Culto", grupo: 'ministro', foto: "/gobierno/fotos/manuel-tovar-rivera.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-relaciones-exteriores-y-culto-mrec", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Licenciado en Derecho por la Universidad Autónoma de Centroamérica, es Máster en Derecho Internacional y Relaciones Internacionales de la Universidad Complutense de Madrid y Doctorado en Ciencias Políticas por la Universidad de Salamanca, entidad en la cual estudió un posgrado en Derecho Administrativo. Ha realizado estudios de actualización profesional en la Universidad de Harvard y London School of Economics and Political Science.\nEn mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Relaciones Exteriores y Culto para el período 2026-2030.\nA lo largo de su trayectoria ha trabajado en el fortalecimiento de las relaciones diplomáticas de Costa Rica, la atracción de inversión y la promoción del país en el ámbito internacional. Como Canciller de la República, lidera la política exterior costarricense, impulsando la cooperación internacional, el diálogo diplomático y la defensa de los intereses del país ante la comunidad internacional." },
  { nombre: "Gerald Campos Valverde", cargo: "Seguridad Pública y Gobernación", institucion: "Ministerio de Seguridad Pública y Gobernación", grupo: 'ministro', foto: "/gobierno/fotos/gerald-campos-valverde.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-gobernacion-policia-y-seguridad-publica", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con una amplia trayectoria en seguridad, investigación criminal y administración pública. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Seguridad Pública para el período 2026-2030.\nA lo largo de su carrera ha ocupado distintos cargos vinculados al fortalecimiento institucional, la seguridad ciudadana y la lucha contra el crimen organizado. Desde el Ministerio de Seguridad Pública lidera las estrategias nacionales orientadas a la protección de la ciudadanía, el fortalecimiento de los cuerpos policiales y la coordinación de acciones para preservar el orden y la seguridad en Costa Rica." },
  { nombre: "Gabriel Aguilar Vargas", cargo: "Justicia y Paz", institucion: "Ministerio de Justicia y Paz", grupo: 'ministro', foto: "/gobierno/fotos/gabriel-aguilar-vargas.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-justicia-y-paz-mjp", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es abogado y funcionario público costarricense con experiencia en derecho, gestión institucional y políticas públicas. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Justicia y Paz para el período 2026-2030.\nA lo largo de su trayectoria ha trabajado en iniciativas relacionadas con el fortalecimiento del sistema de justicia, la convivencia pacífica y la modernización institucional. Desde el Ministerio de Justicia y Paz lidera acciones orientadas a la administración del sistema penitenciario, la promoción de la paz social y el fortalecimiento de políticas enfocadas en la seguridad jurídica y los derechos de la ciudadanía." },
  { nombre: "José Leonardo Sánchez Hernández", cargo: "Educación Pública", institucion: "Ministerio de Educación Pública (MEP)", grupo: 'ministro', foto: "/gobierno/fotos/jose-leonardo-sanchez-hernandez.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-educacion-publica-mep", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con experiencia en gestión educativa, liderazgo académico y desarrollo de políticas públicas en el ámbito de la educación. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Educación Pública para el período 2026-2030.\nA lo largo de su trayectoria ha impulsado iniciativas orientadas al fortalecimiento del sistema educativo, la innovación académica y la mejora de las oportunidades de aprendizaje para la población estudiantil. Desde el Ministerio de Educación Pública lidera estrategias enfocadas en la calidad educativa, la modernización institucional y el acceso a una educación inclusiva y de excelencia para Costa Rica." },
  { nombre: "Efraím Zeledón Leiva", cargo: "Obras Públicas y Transportes", institucion: "Ministerio de Obras Públicas y Transportes (MOPT)", grupo: 'ministro', foto: "/gobierno/fotos/efraim-zeledon-leiva.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministro-de-obras-publicas-y-transportes-mopt", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con experiencia en infraestructura, planificación y gestión de proyectos de transporte y obra pública. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Obras Públicas y Transportes para el período 2026-2030.\nA lo largo de su trayectoria ha participado en iniciativas orientadas al fortalecimiento de la infraestructura nacional, la modernización del transporte y la mejora de la conectividad del país. Desde el Ministerio de Obras Públicas y Transportes lidera proyectos estratégicos enfocados en movilidad, desarrollo vial y modernización de la infraestructura pública para impulsar el crecimiento y la competitividad de Costa Rica." },
  { nombre: "María del Milagro Solórzano León", cargo: "Economía, Industria y Comercio", institucion: "Ministerio de Economía, Industria y Comercio (MEIC)", grupo: 'ministro', foto: "/gobierno/fotos/maria-del-milagro-solorzano-leon.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-economia-industria-y-comercio-meic", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con más de 20 años de experiencia profesional en el sector privado, con énfasis en la defensa de los derechos de los consumidores, la simplificación de trámites y los procedimientos administrativos y de contratación pública. Asimismo, brindó asesoría en temas relevantes a la Cámara de Industria y Comercio Costa Rica-México y a la Cámara Costarricense de la Construcción. En mayo de 2026 fue nombrada por la Presidente Laura Fernández Delgado como Ministra de Economía, Industria y Comercio (MEIC) para el período 2026-2030.\nDesde el Ministerio de Economía, Industria y Comercio lidera iniciativas orientadas al fortalecimiento del sector productivo, el impulso al emprendimiento, la competitividad y la modernización de políticas que promuevan el desarrollo económico y empresarial del país." },
  { nombre: "Juan Gabriel Ramírez Guillén", cargo: "Agricultura y Ganadería", institucion: "Ministerio de Agricultura y Ganadería (MAG)", grupo: 'ministro', foto: "/gobierno/fotos/juan-gabriel-ramirez-guillen.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-agricultura-y-ganaderia-mag", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es ingeniero en agronegocios y funcionario costarricense con más de 19 años de experiencia en producción, exportación, innovación y mercados internacionales. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Agricultura y Ganadería para el período 2026-2030.\nA lo largo de su trayectoria ha trabajado en proyectos relacionados con el fortalecimiento del sector agropecuario y el desarrollo de cadenas productivas, además de colaborar con organismos como la Organización de las Naciones Unidas para la Alimentación y la Agricultura (FAO) y la Promotora del Comercio Exterior de Costa Rica (PROCOMER). Desde el Ministerio de Agricultura y Ganadería lidera estrategias orientadas a impulsar la productividad, la sostenibilidad y la competitividad del agro costarricense, fortaleciendo el acompañamiento a las personas productoras y el desarrollo del sector agrícola nacional." },
  { nombre: "Alexander Sánchez Cabo", cargo: "Salud", institucion: "Ministerio de Salud", grupo: 'ministro', foto: "/gobierno/fotos/alexander-sanchez-cabo.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-salud", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con experiencia en gestión de servicios de salud y administración hospitalaria. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Salud para el período 2026-2030. Previamente se desempeñó como gerente médico interino de la Caja Costarricense de Seguro Social (CCSS), donde participó en iniciativas orientadas al fortalecimiento de la atención médica, la formación de especialistas y la modernización de servicios de salud.\nDesde el Ministerio de Salud lidera estrategias enfocadas en fortalecer el sistema sanitario nacional, impulsar una gestión más eficiente, promover la prevención y garantizar el acceso a servicios de salud de calidad para la población costarricense." },
  { nombre: "Roy Thompson Chacón", cargo: "Trabajo y Seguridad Social", institucion: "Ministerio de Trabajo y Seguridad Social (MTSS)", grupo: 'ministro', foto: "/gobierno/fotos/roy-thompson-chacon.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-trabajo-y-seguridad-social-mtss", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con experiencia en asuntos legislativos, derecho, gestión pública y políticas regulatorias. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Trabajo y Seguridad Social para el período 2026-2030.\nA lo largo de su trayectoria ha participado en procesos relacionados con legislación, desarrollo institucional y coordinación entre sectores públicos y privados. Desde el Ministerio de Trabajo y Seguridad Social lidera iniciativas orientadas a promover el empleo, fortalecer las condiciones laborales, impulsar el diálogo social y generar mayores oportunidades para el desarrollo económico y bienestar de las personas trabajadoras del país." },
  { nombre: "Jorge Rodríguez Vives", cargo: "Cultura y Juventud", institucion: "Ministerio de Cultura y Juventud", grupo: 'ministro', foto: "/gobierno/fotos/jorge-rodriguez-vives.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-cultura-y-juventud-mcj", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Lidera el Ministerio de Cultura y Juventud con el compromiso de fortalecer la identidad cultural y promover el bienestar de la población costarricense. Su labor se centra en diseñar e implementar políticas públicas que impulsen la creatividad, la diversidad cultural y el acceso equitativo a las expresiones artísticas y culturales. Bajo su dirección, el ministerio trabaja para garantizar que la cultura y la juventud sean pilares fundamentales en el desarrollo social y económico del país." },
  { nombre: "Carla Morales Rojas", cargo: "Planificación (MIDEPLAN)", institucion: "Ministerio de Planificación Nacional y Política Económica (MIDEPLAN)", grupo: 'ministro', foto: "/gobierno/fotos/carla-morales-rojas.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-planificacion-nacional-y-politica-economica-mideplan", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es una politóloga con más de 25 años de experiencia en el diseño, implementación y evaluación de políticas públicas. Posee una sólida formación académica que incluye una Maestría en Derechos Humanos de la Universidad Estatal a Distancia, así como una Licenciatura y un Bachillerato en Ciencias Políticas por la Universidad de Costa Rica. Se especializa en áreas de descentralización, desarrollo local y participación ciudadana, destacando por su capacidad de articulación política, negociación y dirección de equipos técnicos para la generación de resultados con impacto social. En mayo de 2026 fue nombrada por la Presidente Laura Fernández Delgado como Ministra de Planificación Nacional y Política Económica para el período 2026-2030. \nA lo largo de su trayectoria ha ocupado puestos de liderazgo en planificación estratégica y gestión pública, además de desempeñarse como consultora para organismos internacionales y docente universitaria. Desde el Ministerio de Planificación Nacional y Política Económica lidera acciones orientadas a fortalecer la modernización del Estado, la planificación estratégica y la articulación de políticas públicas enfocadas en el desarrollo y bienestar del país." },
  { nombre: "Mónica Navarro del Valle", cargo: "Ambiente y Energía", institucion: "Ministerio de Ambiente y Energía (MINAE)", grupo: 'ministro', foto: "/gobierno/fotos/monica-navarro-del-valle.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-ambiente-y-energia-minae", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es abogada y especialista en políticas públicas ambientales, con una trayectoria vinculada a la sostenibilidad, la gestión ambiental y el desarrollo estratégico. En mayo de 2026 fue nombrada por la Presidente Laura Fernández Delgado como Ministra de Ambiente y Energía para el período 2026-2030.\nA lo largo de su carrera ha trabajado en iniciativas relacionadas con la protección ambiental, el desarrollo sostenible y la articulación entre sectores públicos y privados. Desde el Ministerio de Ambiente y Energía lidera estrategias orientadas a la conservación de los recursos naturales, la transición energética, la sostenibilidad y el fortalecimiento de políticas ambientales para el desarrollo de Costa Rica." },
  { nombre: "Guillermo Carazo Ramírez", cargo: "Vivienda y Asentamientos Humanos", institucion: "Ministerio de Vivienda y Asentamientos Humanos (MIVAH)", grupo: 'ministro', foto: "/gobierno/fotos/guillermo-carazo-ramirez.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/index.php/gabinete/ministerio-de-vivienda-y-asentamientos-humanos", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con una trayectoria vinculada al desarrollo urbano, la infraestructura y la planificación territorial. Antes de asumir funciones en el Gobierno, se desempeñó como Director Ejecutivo del Colegio Federado de Ingenieros y de Arquitectos (CFIA), impulsando iniciativas relacionadas con el crecimiento urbano, la construcción y el desarrollo sostenible. En mayo de 2026 fue nombrado por la Presidente Laura Fernández Delgado como Ministro de Vivienda y Asentamientos Humanos para el período 2026-2030.\nDesde el Ministerio de Vivienda y Asentamientos Humanos lidera estrategias orientadas a ampliar el acceso a vivienda digna, fortalecer el desarrollo urbano ordenado y promover proyectos que contribuyan a mejorar la calidad de vida de las familias costarricenses." },
  { nombre: "Indiana Trejos Gallo", cargo: "Comercio Exterior", institucion: "Ministerio de Comercio Exterior (COMEX)", grupo: 'ministro', foto: "/gobierno/fotos/indiana-trejos-gallo.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-comercio-exterior-comex", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Es especialista en comercio exterior y funcionaria pública costarricense con más de dos décadas de experiencia en negociaciones comerciales, facilitación del comercio y gestión pública. En mayo de 2026 fue nombrada por la Presidente Laura Fernández Delgado como Ministra de Comercio Exterior para el período 2026-2030. Previamente se desempeñó como Viceministra de Comercio Exterior y Presidenta del Consejo Nacional de Facilitación del Comercio, liderando iniciativas orientadas a fortalecer la competitividad y la modernización de procesos comerciales del país.\nDesde el Ministerio de Comercio Exterior impulsa estrategias enfocadas en la atracción de inversión, el fortalecimiento de las exportaciones, la apertura de oportunidades para las empresas costarricenses y el posicionamiento de Costa Rica en los mercados internacionales." },
  { nombre: "Paula Bogantes Zamora", cargo: "Ciencia, Innovación y Tecnología", institucion: "Ministerio de Ciencia, Innovación, Tecnología y Telecomunicaciones (MICITT)", grupo: 'ministro', foto: "/gobierno/fotos/paula-bogantes-zamora.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministerio-de-ciencia-innovacion-tecnologia-y-telecomunicaciones-micitt", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Costarricense, máster en Comercio y Mercados Internacionales de LEAD University, así como Bachiller en Administración de Negocios por la Universidad Internacional de las Américas. La señora Bogantes cuenta con una especialidad en liderazgo organizacional por la Universidad de Georgetown y cursa un diplomado en Transformación Digital del Massachusetts Institute of Technology (MIT).\nPrevio a su designación como Ministra de Ciencia, Innovación, Tecnología y Telecomunicaciones (MICITT), la señora Bogantes Zamora se desempeñó como Viceministra de Comercio Exterior de Costa Rica y fue presidenta del Consejo Nacional de Facilitación del Comercio (CONAFAC).\nAdemás, laboró en la Coalición Costarricense de Iniciativas de Desarrollo (CINDE) como gerente de los sectores de Tecnologías Digitales, y Manufactura Avanzada y Tecnologías Limpias. Adicionalmente, se ha desempeñado como consultora para organismos internacionales como el Banco Interamericano de Desarrollo (BID) en materia de políticas públicas en temas como competitividad, innovación y tecnología, en colaboración con el MICITT, la academia y el sector privado.\nAsimismo, colaboró en la elaboración de una propuesta país para la creación de una Agencia de Innovación y un Laboratorio de Innovación Pública.\nBogantes Zamora cuenta con una amplia experiencia en el desarrollo de estrategias de atracción de inversión extranjera para industrias como computación de la nube, ciberseguridad, aeroespacial, automotriz y dispositivos médicos. Habla español e inglés." },
  { nombre: "Arnold Zamora Miranda", cargo: "Comunicación", institucion: "Ministerio de Comunicación", grupo: 'ministro', foto: "/gobierno/fotos/arnold-zamora-miranda.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministro-de-comunicacion-y-enlace", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Lidera el Ministerio de Comunicación y Enlace con el compromiso de fortalecer la transparencia, la rendición de cuentas y la comunicación efectiva entre el Gobierno y la ciudadanía. Su labor se centra en garantizar que la información pública sea accesible, clara y oportuna, promoviendo una cultura de participación y confianza en las instituciones del Estado. Bajo su dirección, el ministerio trabaja para mejorar los canales de comunicación, facilitando el acceso a la información y fomentando un diálogo constructivo entre el Gobierno y la sociedad costarricense." },
  { nombre: "Carlos Andrés Robles Obando", cargo: "Costas, Mares y Pesca", institucion: "Ministerio de Costas, Mares y Pesca", grupo: 'ministro', foto: "/gobierno/fotos/carlos-andres-robles-obando.jpg", fotoCredito: "Asamblea Legislativa de Costa Rica", fuenteUrl: "https://asamblea.go.cr/Diputados/robles_obando/SitePages/Proyectos.aspx", fuenteNombre: "Asamblea Legislativa de Costa Rica", bio: "Es administrador de empresas y exdiputado por Puntarenas en la Asamblea Legislativa durante el periodo 2022-2026. En el Gobierno de Laura Fernández Delgado fue designado Ministro de Costas, Mares y Pesca, una cartera orientada a la atención de los territorios costeros, el sector pesquero y los asuntos marítimos." },
  { nombre: "Yorleni León Marchena", cargo: "Desarrollo Humano e Inclusión Social", institucion: "Ministerio de Desarrollo Humano e Inclusión Social", grupo: 'ministro', foto: "/gobierno/fotos/yorleni-leon-marchena.jpg", fotoCredito: "Presidencia de la República de Costa Rica (CC BY-SA 4.0)", fuenteUrl: "https://www.presidencia.go.cr/gabinete/ministra-de-desarrollo-humano-e-inclusion-social", fuenteNombre: "Presidencia de la República de Costa Rica", bio: "Cuenta con la Licenciatura en Administración de Negocios de la Universidad Interamericana de Costa Rica, es Máster en Desarrollo Económico Local de la Facultad Latinoamericana en Ciencias Sociales (Flacso).\nParticipó en diversos seminarios de postgrado en: Evaluación de Proyectos de FOCEVAL, GIZ y UCR; gerencia de la sostenibilidad y Liderazgo de Incae y Proyectos de Desarrollo de ICAP.\nImpulsó proyectos comunales en materia de infraestructura, competitividad, educación y seguridad con un enfoque de alianzas público-privadas, a través de su actividad como Directora Ejecutiva en la Agencia para el Desarrollo de Pococí.\nFue docente visitante, impartiendo cursos de Experiencia Comunitaria y Comunicación para el Desarrollo y como miembro del equipo técnico del programa de Desarrollo Comunitario de la EARTH.\nEntre sus experiencias laborales trabajó como empresaria y consultora en diversos campos, fue Directora Ejecutiva de la Agencia para el Desarrollo Local de Pococí, fue Asesora de la Presidencia de JAPDEVA y profesora Universitaria de la Universidad de Costa Rica (UCR) y la Universidad Nacional Estatal a Distancia (UNED).\nFue líder activa, apoyó a las comunidades limonenses. En 2016 participó como aspirante a la Vicealcaldía en Pococí. En 2017 alcanzó la candidatura al primer lugar como diputada de la provincia de Limón por el Partido Liberación Nacional (PLN).\nDesde la Asamblea Legislativa trabajó en áreas de interés para el desarrollo de la salud pública y saneamiento ambiental, emprendedurismo, reactivación económica y de la infraestructura, generación de empleo, la mejora en la calidad de la educación, el deporte y la seguridad.", aliases: ['yorleny-leon-marchena'] }
];

export const PRESIDENCIAS: Funcionario[] = [
  { nombre: 'Róger Madrigal López', cargo: 'Banco Central (BCCR)', institucion: 'Banco Central de Costa Rica (BCCR)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Mónica Taylor Hernández', cargo: 'Caja del Seguro Social (CCSS)', institucion: 'Caja Costarricense de Seguro Social (CCSS)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Marco Acuña Mora', cargo: 'Instituto de Electricidad (ICE)', institucion: 'Instituto Costarricense de Electricidad (ICE)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Gabriela Chacón Fernández', cargo: 'Instituto de Seguros (INS)', institucion: 'Instituto Nacional de Seguros (INS)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Karla Montero Víquez', cargo: 'Refinadora (RECOPE)', institucion: 'Refinadora Costarricense de Petróleo (RECOPE)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Lourdes Sáurez Barboza', cargo: 'Acueductos y Alcantarillados (AyA)', institucion: 'Instituto Costarricense de Acueductos y Alcantarillados (AyA)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Paola Nájera Abarca', cargo: 'Junta de Protección Social (JPS)', institucion: 'Junta de Protección Social (JPS)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Edgar Oviedo Blanco', cargo: 'Aprendizaje (INA)', institucion: 'Instituto Nacional de Aprendizaje (INA)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'José David Córdoba Rodríguez', cargo: 'Consejo de Producción (CNP)', institucion: 'Consejo Nacional de Producción (CNP)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'María José Vega Sanabria', cargo: 'Patronato de la Infancia (PANI)', institucion: 'Patronato Nacional de la Infancia (PANI)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Carolina Delgado Ramírez', cargo: 'Instituto de las Mujeres (INAMU)', institucion: 'Instituto Nacional de las Mujeres (INAMU)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Ricardo Quesada Salas', cargo: 'Desarrollo Rural (INDER)', institucion: 'Instituto de Desarrollo Rural (INDER)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Johnny Leiva Badilla', cargo: 'Vivienda y Urbanismo (INVU)', institucion: 'Instituto Nacional de Vivienda y Urbanismo (INVU)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Warner Quesada Céspedes', cargo: 'Puertos del Pacífico (INCOP)', institucion: 'Instituto Costarricense de Puertos del Pacífico (INCOP)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Álvaro Bermúdez Peña', cargo: 'Ferrocarriles (INCOFER)', institucion: 'Instituto Costarricense de Ferrocarriles (INCOFER)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Marcos Vargas Borges', cargo: 'Turismo (ICT)', institucion: 'Instituto Costarricense de Turismo (ICT)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'José Miguel Jiménez Araya', cargo: 'Fomento Municipal (IFAM)', institucion: 'Instituto de Fomento y Asesoría Municipal (IFAM)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Alejandro Picado Eduarte', cargo: 'Emergencias (CNE)', institucion: 'Comisión Nacional de Prevención de Riesgos y Atención de Emergencias (CNE)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Nelson Peña Navarro', cargo: 'Pesca y Acuicultura (INCOPESCA)', institucion: 'Instituto Costarricense de Pesca y Acuicultura (INCOPESCA)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Juan Diego López', cargo: 'Radio y Televisión (SINART)', institucion: 'Sistema Nacional de Radio y Televisión (SINART)', grupo: 'presidencia-ejecutiva' },
  { nombre: 'Martín Vargas Santamaría', cargo: 'Desarrollo Atlántico (JAPDEVA)', institucion: 'Junta de Administración Portuaria y de Desarrollo Económico de la Vertiente Atlántica (JAPDEVA)', grupo: 'presidencia-ejecutiva' },
];

export const FUNCIONARIOS: Funcionario[] = [...PRESIDENCIA, ...MINISTROS, ...PRESIDENCIAS];

export function getFuncionario(slug: string): Funcionario | undefined {
  return FUNCIONARIOS.find((f) => funcionarioSlug(f) === slug || f.aliases?.includes(slug));
}
