export type MundialMatchStatus = 'scheduled' | 'live' | 'finished';

export type MundialEvent = {
  minute: number;
  type: 'goal' | 'yellow-card' | 'red-card' | 'substitution' | 'foul' | 'var' | 'info';
  team?: 'home' | 'away';
  player?: string;
  detail: string;
};

export type MundialMatch = {
  id: string;
  matchNumber: number;
  slug: string;
  phase: string;
  phaseEs: string;
  group: string | null;
  dateLabel: string;
  kickoffUtc: string | null;
  home: string;
  away: string;
  homeRaw: string;
  awayRaw: string;
  venue: string;
  sourceNote: string;
  status?: MundialMatchStatus;
  homeScore?: number | null;
  awayScore?: number | null;
  events?: MundialEvent[];
};

export const MUNDIAL_SOURCE = {
  name: 'FourFourTwo / calendario Mundial 2026 con base en calendario FIFA',
  url: 'https://www.fourfourtwo.com/competition/world-cup-2026-fixtures-and-results',
  officialUrl: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums',
  importedAt: '2026-06-08T10:58:10.871Z',
};

export const MUNDIAL_GROUPS: Record<string, string[]> = {
  "A": [
    "México",
    "Sudáfrica",
    "Corea del Sur",
    "Chequia"
  ],
  "B": [
    "Canadá",
    "Suiza",
    "Qatar",
    "Bosnia y Herzegovina"
  ],
  "C": [
    "Brasil",
    "Marruecos",
    "Haití",
    "Escocia"
  ],
  "D": [
    "Estados Unidos",
    "Paraguay",
    "Australia",
    "Turquía"
  ],
  "E": [
    "Alemania",
    "Curazao",
    "Costa de Marfil",
    "Ecuador"
  ],
  "F": [
    "Países Bajos",
    "Japón",
    "Túnez",
    "Suecia"
  ],
  "G": [
    "Bélgica",
    "Egipto",
    "Irán",
    "Nueva Zelanda"
  ],
  "H": [
    "España",
    "Cabo Verde",
    "Arabia Saudita",
    "Uruguay"
  ],
  "I": [
    "Francia",
    "Senegal",
    "Noruega",
    "Irak"
  ],
  "J": [
    "Argentina",
    "Argelia",
    "Austria",
    "Jordania"
  ],
  "K": [
    "Portugal",
    "Uzbekistán",
    "Colombia",
    "RD Congo"
  ],
  "L": [
    "Inglaterra",
    "Croacia",
    "Ghana",
    "Panamá"
  ]
};

export const MUNDIAL_MATCHES: MundialMatch[] = [
  {
    "id": "m001",
    "matchNumber": 1,
    "slug": "001-mexico-vs-south-africa",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 11, 2026",
    "kickoffUtc": "2026-06-11T19:00:00.000Z",
    "home": "México",
    "away": "Sudáfrica",
    "homeRaw": "Mexico",
    "awayRaw": "South Africa",
    "venue": "Estadio Azteca, Mexico City",
    "sourceNote": "Mexico vs South Africa, Estadio Azteca, Mexico City, 1pm local, 8pm UK"
  },
  {
    "id": "m002",
    "matchNumber": 2,
    "slug": "002-south-korea-vs-czechia",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 11, 2026",
    "kickoffUtc": "2026-06-12T02:00:00.000Z",
    "home": "Corea del Sur",
    "away": "Chequia",
    "homeRaw": "South Korea",
    "awayRaw": "Czechia",
    "venue": "Estadio Akron, Zapopan",
    "sourceNote": "South Korea vs Czechia, Estadio Akron, Zapopan, 8pm local, 3am UK (June 12)"
  },
  {
    "id": "m003",
    "matchNumber": 3,
    "slug": "003-czechia-vs-south-africa",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 18, 2026",
    "kickoffUtc": "2026-06-18T16:00:00.000Z",
    "home": "Chequia",
    "away": "Sudáfrica",
    "homeRaw": "Czechia",
    "awayRaw": "South Africa",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Czechia vs South Africa, Mercedes-Benz Stadium, Atlanta, 12noon local, 5pm UK"
  },
  {
    "id": "m004",
    "matchNumber": 4,
    "slug": "004-mexico-vs-south-korea",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 18, 2026",
    "kickoffUtc": "2026-06-19T01:00:00.000Z",
    "home": "México",
    "away": "Corea del Sur",
    "homeRaw": "Mexico",
    "awayRaw": "South Korea",
    "venue": "Estadio Akron, Zapopan",
    "sourceNote": "Mexico vs South Korea, Estadio Akron, Zapopan, 7pm local, 2am UK (June 19)"
  },
  {
    "id": "m005",
    "matchNumber": 5,
    "slug": "005-czechia-vs-mexico",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-25T01:00:00.000Z",
    "home": "Chequia",
    "away": "México",
    "homeRaw": "Czechia",
    "awayRaw": "Mexico",
    "venue": "Estadio Azteca, Mexico City",
    "sourceNote": "Czechia vs Mexico, Estadio Azteca, Mexico City, 7pm local, 2am UK (June 25)"
  },
  {
    "id": "m006",
    "matchNumber": 6,
    "slug": "006-south-africa-vs-south-korea",
    "phase": "Group A",
    "phaseEs": "Grupo A",
    "group": "A",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-25T01:00:00.000Z",
    "home": "Sudáfrica",
    "away": "Corea del Sur",
    "homeRaw": "South Africa",
    "awayRaw": "South Korea",
    "venue": "Estadio BBVA, Guadalupe",
    "sourceNote": "South Africa vs South Korea, Estadio BBVA, Guadalupe, 7pm local, 2am UK (June 25)"
  },
  {
    "id": "m007",
    "matchNumber": 7,
    "slug": "007-canada-vs-bosnia-and-herzegovina",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 12, 2026",
    "kickoffUtc": "2026-06-12T19:00:00.000Z",
    "home": "Canadá",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Canada",
    "awayRaw": "Bosnia and Herzegovina",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Canada vs Bosnia and Herzegovina, BMO Field, Toronto, 3pm local, 8pm UK"
  },
  {
    "id": "m008",
    "matchNumber": 8,
    "slug": "008-qatar-vs-switzerland",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 13, 2026",
    "kickoffUtc": "2026-06-13T19:00:00.000Z",
    "home": "Qatar",
    "away": "Suiza",
    "homeRaw": "Qatar",
    "awayRaw": "Switzerland",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Qatar vs Switzerland, Levi's Stadium, Santa Clara, 12noon local, 8pm UK"
  },
  {
    "id": "m009",
    "matchNumber": 9,
    "slug": "009-switzerland-vs-bosnia-and-herzegovina",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 18, 2026",
    "kickoffUtc": "2026-06-18T19:00:00.000Z",
    "home": "Suiza",
    "away": "Bosnia y Herzegovina",
    "homeRaw": "Switzerland",
    "awayRaw": "Bosnia and Herzegovina",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Switzerland vs Bosnia and Herzegovina, SoFi Stadium, Inglewood, 12noon local, 8pm UK"
  },
  {
    "id": "m010",
    "matchNumber": 10,
    "slug": "010-canada-vs-qatar",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 18, 2026",
    "kickoffUtc": "2026-06-18T22:00:00.000Z",
    "home": "Canadá",
    "away": "Qatar",
    "homeRaw": "Canada",
    "awayRaw": "Qatar",
    "venue": "BC Place, Vancouver",
    "sourceNote": "Canada vs Qatar, BC Place, Vancouver, 3pm local, 11pm UK"
  },
  {
    "id": "m011",
    "matchNumber": 11,
    "slug": "011-switzerland-vs-canada",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-24T19:00:00.000Z",
    "home": "Suiza",
    "away": "Canadá",
    "homeRaw": "Switzerland",
    "awayRaw": "Canada",
    "venue": "BC Place, Vancouver",
    "sourceNote": "Switzerland vs Canada, BC Place, Vancouver, 12noon local, 8pm UK"
  },
  {
    "id": "m012",
    "matchNumber": 12,
    "slug": "012-bosnia-and-herzegovina-vs-qatar",
    "phase": "Group B",
    "phaseEs": "Grupo B",
    "group": "B",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-24T19:00:00.000Z",
    "home": "Bosnia y Herzegovina",
    "away": "Qatar",
    "homeRaw": "Bosnia and Herzegovina",
    "awayRaw": "Qatar",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "Bosnia and Herzegovina vs Qatar, Lumen Field, Seattle, 12noon local, 8pm UK"
  },
  {
    "id": "m013",
    "matchNumber": 13,
    "slug": "013-brazil-vs-morocco",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 13, 2026",
    "kickoffUtc": "2026-06-13T22:00:00.000Z",
    "home": "Brasil",
    "away": "Marruecos",
    "homeRaw": "Brazil",
    "awayRaw": "Morocco",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Brazil vs Morocco, Gillette Stadium, Foxborough, 6pm local, 11pm UK"
  },
  {
    "id": "m014",
    "matchNumber": 14,
    "slug": "014-haiti-vs-scotland",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 13, 2026",
    "kickoffUtc": "2026-06-14T01:00:00.000Z",
    "home": "Haití",
    "away": "Escocia",
    "homeRaw": "Haiti",
    "awayRaw": "Scotland",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Haiti vs Scotland, MetLife Stadium, East Rutherford, 9pm local, 2am UK (June 14)"
  },
  {
    "id": "m015",
    "matchNumber": 15,
    "slug": "015-scotland-vs-morocco",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 19, 2026",
    "kickoffUtc": "2026-06-19T22:00:00.000Z",
    "home": "Escocia",
    "away": "Marruecos",
    "homeRaw": "Scotland",
    "awayRaw": "Morocco",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "Scotland vs Morocco, Lincoln Financial Field, Philadelphia, 6pm local, 11pm UK"
  },
  {
    "id": "m016",
    "matchNumber": 16,
    "slug": "016-brazil-vs-haiti",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 19, 2026",
    "kickoffUtc": "2026-06-20T01:00:00.000Z",
    "home": "Brasil",
    "away": "Haití",
    "homeRaw": "Brazil",
    "awayRaw": "Haiti",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Brazil vs Haiti, Gillette Stadium, Foxborough, 9pm local, 2am UK (June 20)"
  },
  {
    "id": "m017",
    "matchNumber": 17,
    "slug": "017-scotland-vs-brazil",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-24T22:00:00.000Z",
    "home": "Escocia",
    "away": "Brasil",
    "homeRaw": "Scotland",
    "awayRaw": "Brazil",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Scotland vs Brazil, Hard Rock Stadium, Miami Gardens, 6pm local, 11pm UK"
  },
  {
    "id": "m018",
    "matchNumber": 18,
    "slug": "018-morocco-vs-haiti",
    "phase": "Group C",
    "phaseEs": "Grupo C",
    "group": "C",
    "dateLabel": "June 24, 2026",
    "kickoffUtc": "2026-06-24T22:00:00.000Z",
    "home": "Marruecos",
    "away": "Haití",
    "homeRaw": "Morocco",
    "awayRaw": "Haiti",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Morocco vs Haiti, Mercedes-Benz Stadium, Atlanta, 6pm local, 11pm UK"
  },
  {
    "id": "m019",
    "matchNumber": 19,
    "slug": "019-united-states-vs-paraguay",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 12, 2026",
    "kickoffUtc": "2026-06-13T01:00:00.000Z",
    "home": "Estados Unidos",
    "away": "Paraguay",
    "homeRaw": "United States",
    "awayRaw": "Paraguay",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "United States vs Paraguay, SoFi Stadium, Inglewood, 6pm local, 2am UK (June 13)"
  },
  {
    "id": "m020",
    "matchNumber": 20,
    "slug": "020-australia-vs-turkiye",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 13, 2026",
    "kickoffUtc": "2026-06-14T04:00:00.000Z",
    "home": "Australia",
    "away": "Turquía",
    "homeRaw": "Australia",
    "awayRaw": "Turkiye",
    "venue": "BC Place, Vancouver",
    "sourceNote": "Australia vs Turkiye, BC Place, Vancouver, 9pm local, 5am UK (June 14)"
  },
  {
    "id": "m021",
    "matchNumber": 21,
    "slug": "021-turkiye-vs-paraguay",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 19, 2026",
    "kickoffUtc": "2026-06-20T04:00:00.000Z",
    "home": "Turquía",
    "away": "Paraguay",
    "homeRaw": "Turkiye",
    "awayRaw": "Paraguay",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Turkiye vs Paraguay, Levi's Stadium, Santa Clara, 9pm local, 5am UK (June 20)"
  },
  {
    "id": "m022",
    "matchNumber": 22,
    "slug": "022-united-states-vs-australia",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 19, 2026",
    "kickoffUtc": "2026-06-19T19:00:00.000Z",
    "home": "Estados Unidos",
    "away": "Australia",
    "homeRaw": "United States",
    "awayRaw": "Australia",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "United States vs Australia, Lumen Field, Seattle, 12noon local, 8pm UK"
  },
  {
    "id": "m023",
    "matchNumber": 23,
    "slug": "023-turkiye-vs-united-states",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-26T02:00:00.000Z",
    "home": "Turquía",
    "away": "Estados Unidos",
    "homeRaw": "Turkiye",
    "awayRaw": "United States",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Turkiye vs United States, SoFi Stadium, Inglewood, 7pm local, 3am UK (June 26)"
  },
  {
    "id": "m024",
    "matchNumber": 24,
    "slug": "024-paraguay-vs-australia",
    "phase": "Group D",
    "phaseEs": "Grupo D",
    "group": "D",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-26T02:00:00.000Z",
    "home": "Paraguay",
    "away": "Australia",
    "homeRaw": "Paraguay",
    "awayRaw": "Australia",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Paraguay vs Australia, Levi's Stadium, Santa Clara, 7pm local, 3am UK (June 26)"
  },
  {
    "id": "m025",
    "matchNumber": 25,
    "slug": "025-ivory-coast-vs-ecuador",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 14, 2026",
    "kickoffUtc": "2026-06-14T17:00:00.000Z",
    "home": "Costa de Marfil",
    "away": "Ecuador",
    "homeRaw": "Ivory Coast",
    "awayRaw": "Ecuador",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "Ivory Coast vs Ecuador, Lincoln Financial Field, Philadelphia, 7pm local, 6pm UK"
  },
  {
    "id": "m026",
    "matchNumber": 26,
    "slug": "026-germany-vs-curacao",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 14, 2026",
    "kickoffUtc": "2026-06-14T23:00:00.000Z",
    "home": "Alemania",
    "away": "Curazao",
    "homeRaw": "Germany",
    "awayRaw": "Curacao",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Germany vs Curacao, NRG Stadium, Houston, 12noon local, Midnight UK (June 15)"
  },
  {
    "id": "m027",
    "matchNumber": 27,
    "slug": "027-germany-vs-ivory-coast",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 20, 2026",
    "kickoffUtc": "2026-06-20T20:00:00.000Z",
    "home": "Alemania",
    "away": "Costa de Marfil",
    "homeRaw": "Germany",
    "awayRaw": "Ivory Coast",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Germany vs Ivory Coast, BMO Field, Toronto, 4pm local, 9pm UK"
  },
  {
    "id": "m028",
    "matchNumber": 28,
    "slug": "028-ecuador-vs-curacao",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 20, 2026",
    "kickoffUtc": "2026-06-21T00:00:00.000Z",
    "home": "Ecuador",
    "away": "Curazao",
    "homeRaw": "Ecuador",
    "awayRaw": "Curacao",
    "venue": "Arrowhead Stadium, Kansas City",
    "sourceNote": "Ecuador vs Curacao, Arrowhead Stadium, Kansas City, 7pm local, 1am UK (June 21)"
  },
  {
    "id": "m029",
    "matchNumber": 29,
    "slug": "029-curacao-vs-ivory-coast",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-25T20:00:00.000Z",
    "home": "Curazao",
    "away": "Costa de Marfil",
    "homeRaw": "Curacao",
    "awayRaw": "Ivory Coast",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "Curacao vs Ivory Coast, Lincoln Financial Field, Philadelphia, 4pm local, 9pm UK"
  },
  {
    "id": "m030",
    "matchNumber": 30,
    "slug": "030-ecuador-vs-germany",
    "phase": "Group E",
    "phaseEs": "Grupo E",
    "group": "E",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-25T20:00:00.000Z",
    "home": "Ecuador",
    "away": "Alemania",
    "homeRaw": "Ecuador",
    "awayRaw": "Germany",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Ecuador vs Germany, MetLife Stadium, East Rutherford, 4pm local, 9pm UK"
  },
  {
    "id": "m031",
    "matchNumber": 31,
    "slug": "031-netherlands-vs-japan",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 14, 2026",
    "kickoffUtc": "2026-06-14T20:00:00.000Z",
    "home": "Países Bajos",
    "away": "Japón",
    "homeRaw": "Netherlands",
    "awayRaw": "Japan",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Netherlands vs Japan, AT&T Stadium, Arlington, 3pm local, 9pm UK"
  },
  {
    "id": "m032",
    "matchNumber": 32,
    "slug": "032-sweden-vs-tunisia",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 14, 2026",
    "kickoffUtc": "2026-06-15T02:00:00.000Z",
    "home": "Suecia",
    "away": "Túnez",
    "homeRaw": "Sweden",
    "awayRaw": "Tunisia",
    "venue": "Estadio BBVA, Guadalupe",
    "sourceNote": "Sweden vs Tunisia, Estadio BBVA, Guadalupe, 8pm local, 3am UK (June 15)"
  },
  {
    "id": "m033",
    "matchNumber": 33,
    "slug": "033-netherlands-vs-sweden",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 20, 2026",
    "kickoffUtc": "2026-06-20T17:00:00.000Z",
    "home": "Países Bajos",
    "away": "Suecia",
    "homeRaw": "Netherlands",
    "awayRaw": "Sweden",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Netherlands vs Sweden, NRG Stadium, Houston, 12noon local, 6pm UK"
  },
  {
    "id": "m034",
    "matchNumber": 34,
    "slug": "034-tunisia-vs-japan",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 20, 2026",
    "kickoffUtc": "2026-06-21T04:00:00.000Z",
    "home": "Túnez",
    "away": "Japón",
    "homeRaw": "Tunisia",
    "awayRaw": "Japan",
    "venue": "Estadio BBVA, Guadalupe",
    "sourceNote": "Tunisia vs Japan, Estadio BBVA, Guadalupe, 10pm local, 5am UK (June 21)"
  },
  {
    "id": "m035",
    "matchNumber": 35,
    "slug": "035-japan-vs-sweden",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-25T23:00:00.000Z",
    "home": "Japón",
    "away": "Suecia",
    "homeRaw": "Japan",
    "awayRaw": "Sweden",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Japan vs Sweden, AT&T Stadium, Arlington, 6pm local, Midnight UK (June 26)"
  },
  {
    "id": "m036",
    "matchNumber": 36,
    "slug": "036-tunisia-vs-netherlands",
    "phase": "Group F",
    "phaseEs": "Grupo F",
    "group": "F",
    "dateLabel": "June 25, 2026",
    "kickoffUtc": "2026-06-25T23:00:00.000Z",
    "home": "Túnez",
    "away": "Países Bajos",
    "homeRaw": "Tunisia",
    "awayRaw": "Netherlands",
    "venue": "Arrowhead Stadium, Kansas City",
    "sourceNote": "Tunisia vs Netherlands, Arrowhead Stadium, Kansas City, 6pm local, Midnight UK (June 26)"
  },
  {
    "id": "m037",
    "matchNumber": 37,
    "slug": "037-iran-vs-new-zealand",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 15, 2026",
    "kickoffUtc": "2026-06-16T01:00:00.000Z",
    "home": "Irán",
    "away": "Nueva Zelanda",
    "homeRaw": "Iran",
    "awayRaw": "New Zealand",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Iran vs New Zealand, SoFi Stadium, Inglewood, 6pm local, 2am UK (June 16)"
  },
  {
    "id": "m038",
    "matchNumber": 38,
    "slug": "038-belgium-vs-egypt",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 15, 2026",
    "kickoffUtc": "2026-06-15T19:00:00.000Z",
    "home": "Bélgica",
    "away": "Egipto",
    "homeRaw": "Belgium",
    "awayRaw": "Egypt",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "Belgium vs Egypt, Lumen Field, Seattle, 12noon local, 8pm UK"
  },
  {
    "id": "m039",
    "matchNumber": 39,
    "slug": "039-belgium-vs-iran",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 21, 2026",
    "kickoffUtc": "2026-06-21T19:00:00.000Z",
    "home": "Bélgica",
    "away": "Irán",
    "homeRaw": "Belgium",
    "awayRaw": "Iran",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Belgium vs Iran, SoFi Stadium, Inglewood, 12noon local, 8pm UK"
  },
  {
    "id": "m040",
    "matchNumber": 40,
    "slug": "040-new-zealand-vs-egypt",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 21, 2026",
    "kickoffUtc": "2026-06-22T01:00:00.000Z",
    "home": "Nueva Zelanda",
    "away": "Egipto",
    "homeRaw": "New Zealand",
    "awayRaw": "Egypt",
    "venue": "BC Place, Vancouver",
    "sourceNote": "New Zealand vs Egypt, BC Place, Vancouver, 6pm local, 2am UK (June 22)"
  },
  {
    "id": "m041",
    "matchNumber": 41,
    "slug": "041-egypt-vs-iran",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-27T03:00:00.000Z",
    "home": "Egipto",
    "away": "Irán",
    "homeRaw": "Egypt",
    "awayRaw": "Iran",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "Egypt vs Iran, Lumen Field, Seattle, 8pm local, 4am UK (June 27)"
  },
  {
    "id": "m042",
    "matchNumber": 42,
    "slug": "042-new-zealand-vs-belgium",
    "phase": "Group G",
    "phaseEs": "Grupo G",
    "group": "G",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-27T03:00:00.000Z",
    "home": "Nueva Zelanda",
    "away": "Bélgica",
    "homeRaw": "New Zealand",
    "awayRaw": "Belgium",
    "venue": "BC Place, Vancouver",
    "sourceNote": "New Zealand vs Belgium, BC Place, Vancouver, 8pm local, 4am UK (June 27)"
  },
  {
    "id": "m043",
    "matchNumber": 43,
    "slug": "043-saudi-arabia-vs-uruguay",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 15, 2026",
    "kickoffUtc": "2026-06-15T22:00:00.000Z",
    "home": "Arabia Saudita",
    "away": "Uruguay",
    "homeRaw": "Saudi Arabia",
    "awayRaw": "Uruguay",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Saudi Arabia vs Uruguay, Hard Rock Stadium, Miami Gardens, 6pm local, 11pm UK"
  },
  {
    "id": "m044",
    "matchNumber": 44,
    "slug": "044-spain-vs-cape-verde",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 15, 2026",
    "kickoffUtc": "2026-06-15T16:00:00.000Z",
    "home": "España",
    "away": "Cabo Verde",
    "homeRaw": "Spain",
    "awayRaw": "Cape Verde",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Spain vs Cape Verde, Mercedes-Benz Stadium, Atlanta, 12noon local, 5pm UK"
  },
  {
    "id": "m045",
    "matchNumber": 45,
    "slug": "045-uruguay-vs-cape-verde",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 21, 2026",
    "kickoffUtc": "2026-06-21T22:00:00.000Z",
    "home": "Uruguay",
    "away": "Cabo Verde",
    "homeRaw": "Uruguay",
    "awayRaw": "Cape Verde",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Uruguay vs Cape Verde, Hard Rock Stadium, Miami Gardens, 6pm local, 11pm UK"
  },
  {
    "id": "m046",
    "matchNumber": 46,
    "slug": "046-spain-vs-saudi-arabia",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 21, 2026",
    "kickoffUtc": "2026-06-21T16:00:00.000Z",
    "home": "España",
    "away": "Arabia Saudita",
    "homeRaw": "Spain",
    "awayRaw": "Saudi Arabia",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Spain vs Saudi Arabia, Mercedes-Benz Stadium, Atlanta, 12noon local, 5pm UK"
  },
  {
    "id": "m047",
    "matchNumber": 47,
    "slug": "047-cape-verde-vs-saudi-arabia",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-27T00:00:00.000Z",
    "home": "Cabo Verde",
    "away": "Arabia Saudita",
    "homeRaw": "Cape Verde",
    "awayRaw": "Saudi Arabia",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Cape Verde vs Saudi Arabia, NRG Stadium, Houston, 7pm local, 1am UK (June 27)"
  },
  {
    "id": "m048",
    "matchNumber": 48,
    "slug": "048-uruguay-vs-spain",
    "phase": "Group H",
    "phaseEs": "Grupo H",
    "group": "H",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-27T00:00:00.000Z",
    "home": "Uruguay",
    "away": "España",
    "homeRaw": "Uruguay",
    "awayRaw": "Spain",
    "venue": "Estadio Akron, Zapopan",
    "sourceNote": "Uruguay vs Spain, Estadio Akron, Zapopan, 6pm local 1am UK (June 27)"
  },
  {
    "id": "m049",
    "matchNumber": 49,
    "slug": "049-france-vs-senegal",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 16, 2026",
    "kickoffUtc": "2026-06-16T19:00:00.000Z",
    "home": "Francia",
    "away": "Senegal",
    "homeRaw": "France",
    "awayRaw": "Senegal",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "France vs Senegal, MetLife Stadium, East Rutherford, 3pm local, 8pm UK"
  },
  {
    "id": "m050",
    "matchNumber": 50,
    "slug": "050-iraq-vs-norway",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 16, 2026",
    "kickoffUtc": "2026-06-16T22:00:00.000Z",
    "home": "Irak",
    "away": "Noruega",
    "homeRaw": "Iraq",
    "awayRaw": "Norway",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Iraq vs Norway, Gillette Stadium, Foxborough, 6pm local, 11pm UK"
  },
  {
    "id": "m051",
    "matchNumber": 51,
    "slug": "051-norway-vs-senegal",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 22, 2026",
    "kickoffUtc": "2026-06-23T00:00:00.000Z",
    "home": "Noruega",
    "away": "Senegal",
    "homeRaw": "Norway",
    "awayRaw": "Senegal",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Norway vs Senegal, MetLife Stadium, East Rutherford, 8pm local, 1am UK (June 23)"
  },
  {
    "id": "m052",
    "matchNumber": 52,
    "slug": "052-france-vs-iraq",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 22, 2026",
    "kickoffUtc": "2026-06-22T21:00:00.000Z",
    "home": "Francia",
    "away": "Irak",
    "homeRaw": "France",
    "awayRaw": "Iraq",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "France vs Iraq, Lincoln Financial Field, Philadelphia, 5pm local, 10pm UK"
  },
  {
    "id": "m053",
    "matchNumber": 53,
    "slug": "053-norway-vs-france",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-26T19:00:00.000Z",
    "home": "Noruega",
    "away": "Francia",
    "homeRaw": "Norway",
    "awayRaw": "France",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Norway vs France, Gillette Stadium, Foxborough, 3pm local, 8pm UK"
  },
  {
    "id": "m054",
    "matchNumber": 54,
    "slug": "054-senegal-vs-iraq",
    "phase": "Group I",
    "phaseEs": "Grupo I",
    "group": "I",
    "dateLabel": "June 26, 2026",
    "kickoffUtc": "2026-06-26T19:00:00.000Z",
    "home": "Senegal",
    "away": "Irak",
    "homeRaw": "Senegal",
    "awayRaw": "Iraq",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Senegal vs Iraq, BMO Field, Toronto, 3pm local, 8pm UK"
  },
  {
    "id": "m055",
    "matchNumber": 55,
    "slug": "055-argentina-vs-algeria-arrowhead-stadium",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 16, 2026",
    "kickoffUtc": "2026-06-17T01:00:00.000Z",
    "home": "Argentina",
    "away": "Argelia",
    "homeRaw": "Argentina",
    "awayRaw": "Algeria",
    "venue": "Kansas City",
    "sourceNote": "Argentina vs Algeria, Arrowhead Stadium, Kansas City, 8pm local, 2am UK (June 17)"
  },
  {
    "id": "m056",
    "matchNumber": 56,
    "slug": "056-austria-vs-jordan",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 16, 2026",
    "kickoffUtc": "2026-06-17T04:00:00.000Z",
    "home": "Austria",
    "away": "Jordania",
    "homeRaw": "Austria",
    "awayRaw": "Jordan",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Austria vs Jordan, Levi's Stadium, Santa Clara, 9pm local, 5am UK (June 17)"
  },
  {
    "id": "m057",
    "matchNumber": 57,
    "slug": "057-argentina-vs-austria",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 22, 2026",
    "kickoffUtc": "2026-06-22T17:00:00.000Z",
    "home": "Argentina",
    "away": "Austria",
    "homeRaw": "Argentina",
    "awayRaw": "Austria",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Argentina vs Austria, AT&T Stadium, Arlington, 12noon local, 6pm UK"
  },
  {
    "id": "m058",
    "matchNumber": 58,
    "slug": "058-jordan-vs-algeria",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 22, 2026",
    "kickoffUtc": "2026-06-23T03:00:00.000Z",
    "home": "Jordania",
    "away": "Argelia",
    "homeRaw": "Jordan",
    "awayRaw": "Algeria",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Jordan vs Algeria, Levi's Stadium, Santa Clara, 8pm local, 4am UK (June 23)"
  },
  {
    "id": "m059",
    "matchNumber": 59,
    "slug": "059-algeria-vs-austria",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-28T02:00:00.000Z",
    "home": "Argelia",
    "away": "Austria",
    "homeRaw": "Algeria",
    "awayRaw": "Austria",
    "venue": "Arrowhead Stadium, Kansas City",
    "sourceNote": "Algeria vs Austria, Arrowhead Stadium, Kansas City, 9pm local, 3am UK (June 28)"
  },
  {
    "id": "m060",
    "matchNumber": 60,
    "slug": "060-jordan-vs-argentina",
    "phase": "Group J",
    "phaseEs": "Grupo J",
    "group": "J",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-28T02:00:00.000Z",
    "home": "Jordania",
    "away": "Argentina",
    "homeRaw": "Jordan",
    "awayRaw": "Argentina",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Jordan vs Argentina, AT&T Stadium, Arlington, 9pm local, 3am UK (June 28)"
  },
  {
    "id": "m061",
    "matchNumber": 61,
    "slug": "061-portugal-vs-dr-congo",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 17, 2026",
    "kickoffUtc": "2026-06-17T17:00:00.000Z",
    "home": "Portugal",
    "away": "RD Congo",
    "homeRaw": "Portugal",
    "awayRaw": "DR Congo",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Portugal vs DR Congo, NRG Stadium, Houston, 12noon local, 6pm UK"
  },
  {
    "id": "m062",
    "matchNumber": 62,
    "slug": "062-uzbekistan-vs-colombia",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 17, 2026",
    "kickoffUtc": "2026-06-18T02:00:00.000Z",
    "home": "Uzbekistán",
    "away": "Colombia",
    "homeRaw": "Uzbekistan",
    "awayRaw": "Colombia",
    "venue": "Estadio Azteca, Mexico City",
    "sourceNote": "Uzbekistan vs Colombia, Estadio Azteca, Mexico City, 8pm local, 3am UK (June 18)"
  },
  {
    "id": "m063",
    "matchNumber": 63,
    "slug": "063-portugal-vs-uzbekistan",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 23, 2026",
    "kickoffUtc": "2026-06-23T17:00:00.000Z",
    "home": "Portugal",
    "away": "Uzbekistán",
    "homeRaw": "Portugal",
    "awayRaw": "Uzbekistan",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Portugal vs Uzbekistan, NRG Stadium, Houston, 12noon local, 6pm UK"
  },
  {
    "id": "m064",
    "matchNumber": 64,
    "slug": "064-colombia-vs-dr-congo",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 23, 2026",
    "kickoffUtc": "2026-06-24T02:00:00.000Z",
    "home": "Colombia",
    "away": "RD Congo",
    "homeRaw": "Colombia",
    "awayRaw": "DR Congo",
    "venue": "Estadio Akron, Zapopan",
    "sourceNote": "Colombia vs DR Congo, Estadio Akron, Zapopan, 8pm local, 3am UK (June 24)"
  },
  {
    "id": "m065",
    "matchNumber": 65,
    "slug": "065-colombia-vs-portugal",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-27T23:30:00.000Z",
    "home": "Colombia",
    "away": "Portugal",
    "homeRaw": "Colombia",
    "awayRaw": "Portugal",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Colombia vs Portugal, Hard Rock Stadium, Miami Gardens, 7.30pm local, 0.30am UK (June 28)"
  },
  {
    "id": "m066",
    "matchNumber": 66,
    "slug": "066-dr-congo-vs-uzbekistan",
    "phase": "Group K",
    "phaseEs": "Grupo K",
    "group": "K",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-27T23:30:00.000Z",
    "home": "RD Congo",
    "away": "Uzbekistán",
    "homeRaw": "DR Congo",
    "awayRaw": "Uzbekistan",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "DR Congo vs Uzbekistan, Mercedes-Benz Stadium, Atlanta, 7.30pm local, 0.30am UK (June 28)"
  },
  {
    "id": "m067",
    "matchNumber": 67,
    "slug": "067-ghana-vs-panama",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 17, 2026",
    "kickoffUtc": "2026-06-17T23:00:00.000Z",
    "home": "Ghana",
    "away": "Panamá",
    "homeRaw": "Ghana",
    "awayRaw": "Panama",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Ghana vs Panama, BMO Field, Toronto, 7pm local, Midnight UK (June 18)"
  },
  {
    "id": "m068",
    "matchNumber": 68,
    "slug": "068-england-vs-croatia",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 17, 2026",
    "kickoffUtc": "2026-06-17T20:00:00.000Z",
    "home": "Inglaterra",
    "away": "Croacia",
    "homeRaw": "England",
    "awayRaw": "Croatia",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "England vs Croatia, AT&T Stadium, Arlington, 3pm local, 9pm UK"
  },
  {
    "id": "m069",
    "matchNumber": 69,
    "slug": "069-england-vs-ghana",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 23, 2026",
    "kickoffUtc": "2026-06-23T20:00:00.000Z",
    "home": "Inglaterra",
    "away": "Ghana",
    "homeRaw": "England",
    "awayRaw": "Ghana",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "England vs Ghana, Gillette Stadium, Foxborough, 4pm local, 9pm UK"
  },
  {
    "id": "m070",
    "matchNumber": 70,
    "slug": "070-panama-vs-croatia",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 23, 2026",
    "kickoffUtc": "2026-06-23T23:00:00.000Z",
    "home": "Panamá",
    "away": "Croacia",
    "homeRaw": "Panama",
    "awayRaw": "Croatia",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Panama vs Croatia, BMO Field, Toronto, 7pm local, Midnight UK (June 24)"
  },
  {
    "id": "m071",
    "matchNumber": 71,
    "slug": "071-panama-vs-england",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-27T21:00:00.000Z",
    "home": "Panamá",
    "away": "Inglaterra",
    "homeRaw": "Panama",
    "awayRaw": "England",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Panama vs England, MetLife Stadium, East Rutherford, 5pm local, 10pm UK"
  },
  {
    "id": "m072",
    "matchNumber": 72,
    "slug": "072-croatia-vs-ghana",
    "phase": "Group L",
    "phaseEs": "Grupo L",
    "group": "L",
    "dateLabel": "June 27, 2026",
    "kickoffUtc": "2026-06-27T21:00:00.000Z",
    "home": "Croacia",
    "away": "Ghana",
    "homeRaw": "Croatia",
    "awayRaw": "Ghana",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "Croatia vs Ghana, Lincoln Financial Field, Philadelphia, 5pm local, 10pm UK"
  },
  {
    "id": "m073",
    "matchNumber": 73,
    "slug": "073-runner-up-group-a-vs-runner-up-group-b",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 28, 2026",
    "kickoffUtc": null,
    "home": "Segundo Grupo A",
    "away": "Segundo Grupo B",
    "homeRaw": "Runner-up Group A",
    "awayRaw": "Runner-up Group B",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Runner-up Group A vs Runner-up Group B, SoFi Stadium, Inglewood"
  },
  {
    "id": "m074",
    "matchNumber": 74,
    "slug": "074-winner-group-e-vs-3rd-group-a-b-c-d-f",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 29, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo E",
    "away": "Tercero Grupo A/B/C/D/F",
    "homeRaw": "Winner Group E",
    "awayRaw": "3rd Group A/B/C/D/F",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Winner Group E vs 3rd Group A/B/C/D/F, Gillette Stadium, Foxborough"
  },
  {
    "id": "m075",
    "matchNumber": 75,
    "slug": "075-winner-group-f-vs-runner-up-group-c",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 29, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo F",
    "away": "Segundo Grupo C",
    "homeRaw": "Winner Group F",
    "awayRaw": "Runner-up Group C",
    "venue": "Estadio BBVA, Guadalupe",
    "sourceNote": "Winner Group F vs Runner-up Group C, Estadio BBVA, Guadalupe"
  },
  {
    "id": "m076",
    "matchNumber": 76,
    "slug": "076-winner-group-c-vs-runner-up-group-f",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 29, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo C",
    "away": "Segundo Grupo F",
    "homeRaw": "Winner Group C",
    "awayRaw": "Runner-up Group F",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Winner Group C vs Runner-up Group F, NRG Stadium, Houston"
  },
  {
    "id": "m077",
    "matchNumber": 77,
    "slug": "077-winner-group-i-vs-3rd-group-c-d-f-g-h",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 30, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo I",
    "away": "Tercero Grupo C/D/F/G/H",
    "homeRaw": "Winner Group I",
    "awayRaw": "3rd Group C/D/F/G/H",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Winner Group I vs 3rd Group C/D/F/G/H, MetLife Stadium, East Rutherford"
  },
  {
    "id": "m078",
    "matchNumber": 78,
    "slug": "078-runner-up-group-e-vs-runner-up-group-i",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 30, 2026",
    "kickoffUtc": null,
    "home": "Segundo Grupo E",
    "away": "Segundo Grupo I",
    "homeRaw": "Runner-up Group E",
    "awayRaw": "Runner-up Group I",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Runner-up Group E vs Runner-up Group I, AT&T Stadium, Arlington"
  },
  {
    "id": "m079",
    "matchNumber": 79,
    "slug": "079-winner-group-a-vs-3rd-group-c-e-f-h-i",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "June 30, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo A",
    "away": "Tercero Grupo C/E/F/H/I",
    "homeRaw": "Winner Group A",
    "awayRaw": "3rd Group C/E/F/H/I",
    "venue": "Estadio Azteca, Mexico City",
    "sourceNote": "Winner Group A vs 3rd Group C/E/F/H/I, Estadio Azteca, Mexico City"
  },
  {
    "id": "m080",
    "matchNumber": 80,
    "slug": "080-winner-group-l-vs-3rd-group-e-h-i-j-k",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 1, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo L",
    "away": "Tercero Grupo E/H/I/J/K",
    "homeRaw": "Winner Group L",
    "awayRaw": "3rd Group E/H/I/J/K",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Winner Group L vs 3rd Group E/H/I/J/K, Mercedes-Benz Stadium, Atlanta"
  },
  {
    "id": "m081",
    "matchNumber": 81,
    "slug": "081-winner-group-d-vs-3rd-group-b-e-f-i-j",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 1, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo D",
    "away": "Tercero Grupo B/E/F/I/J",
    "homeRaw": "Winner Group D",
    "awayRaw": "3rd Group B/E/F/I/J",
    "venue": "Levi's Stadium, Santa Clara",
    "sourceNote": "Winner Group D vs 3rd Group B/E/F/I/J, Levi's Stadium, Santa Clara"
  },
  {
    "id": "m082",
    "matchNumber": 82,
    "slug": "082-winner-group-g-vs-3rd-group-a-e-h-i-j",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 1, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo G",
    "away": "Tercero Grupo A/E/H/I/J",
    "homeRaw": "Winner Group G",
    "awayRaw": "3rd Group A/E/H/I/J",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "Winner Group G vs 3rd Group A/E/H/I/J, Lumen Field, Seattle"
  },
  {
    "id": "m083",
    "matchNumber": 83,
    "slug": "083-runner-up-group-k-vs-runner-up-group-l",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 2, 2026",
    "kickoffUtc": null,
    "home": "Segundo Grupo K",
    "away": "Segundo Grupo L",
    "homeRaw": "Runner-up Group K",
    "awayRaw": "Runner-up Group L",
    "venue": "BMO Field, Toronto",
    "sourceNote": "Runner-up Group K vs Runner-up Group L, BMO Field, Toronto"
  },
  {
    "id": "m084",
    "matchNumber": 84,
    "slug": "084-winner-group-h-vs-runner-up-group-j",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 2, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo H",
    "away": "Segundo Grupo J",
    "homeRaw": "Winner Group H",
    "awayRaw": "Runner-up Group J",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Winner Group H vs Runner-up Group J, SoFi Stadium, Inglewood"
  },
  {
    "id": "m085",
    "matchNumber": 85,
    "slug": "085-winner-group-b-vs-3rd-group-e-f-g-i-j",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 2, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo B",
    "away": "Tercero Grupo E/F/G/I/J",
    "homeRaw": "Winner Group B",
    "awayRaw": "3rd Group E/F/G/I/J",
    "venue": "BC Place, Vancouver",
    "sourceNote": "Winner Group B vs 3rd Group E/F/G/I/J, BC Place, Vancouver"
  },
  {
    "id": "m086",
    "matchNumber": 86,
    "slug": "086-winner-group-j-vs-runner-up-group-h",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 3, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo J",
    "away": "Segundo Grupo H",
    "homeRaw": "Winner Group J",
    "awayRaw": "Runner-up Group H",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Winner Group J vs Runner-up Group H, Hard Rock Stadium, Miami Gardens"
  },
  {
    "id": "m087",
    "matchNumber": 87,
    "slug": "087-winner-group-k-vs-3rd-group-d-e-i-j-l",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 3, 2026",
    "kickoffUtc": null,
    "home": "Ganador Grupo K",
    "away": "Tercero Grupo D/E/I/J/L",
    "homeRaw": "Winner Group K",
    "awayRaw": "3rd Group D/E/I/J/L",
    "venue": "Arrowhead Stadium, Kansas City",
    "sourceNote": "Winner Group K vs 3rd Group D/E/I/J/L, Arrowhead Stadium, Kansas City"
  },
  {
    "id": "m088",
    "matchNumber": 88,
    "slug": "088-runner-up-group-d-vs-runner-up-group-g",
    "phase": "Round of 32",
    "phaseEs": "Dieciseisavos de final",
    "group": null,
    "dateLabel": "July 3, 2026",
    "kickoffUtc": null,
    "home": "Segundo Grupo D",
    "away": "Segundo Grupo G",
    "homeRaw": "Runner-up Group D",
    "awayRaw": "Runner-up Group G",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Runner-up Group D vs Runner-up Group G, AT&T Stadium, Arlington"
  },
  {
    "id": "m089",
    "matchNumber": 89,
    "slug": "089-winner-match-74-vs-winner-match-77",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 4, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 74",
    "away": "Ganador Partido 77",
    "homeRaw": "Winner Match 74",
    "awayRaw": "Winner Match 77",
    "venue": "Lincoln Financial Field, Philadelphia",
    "sourceNote": "Winner Match 74 vs Winner Match 77, Lincoln Financial Field, Philadelphia"
  },
  {
    "id": "m090",
    "matchNumber": 90,
    "slug": "090-winner-match-73-vs-winner-match-75",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 4, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 73",
    "away": "Ganador Partido 75",
    "homeRaw": "Winner Match 73",
    "awayRaw": "Winner Match 75",
    "venue": "NRG Stadium, Houston",
    "sourceNote": "Winner Match 73 vs Winner Match 75, NRG Stadium, Houston"
  },
  {
    "id": "m091",
    "matchNumber": 91,
    "slug": "091-winner-match-76-vs-winner-match-78",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 5, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 76",
    "away": "Ganador Partido 78",
    "homeRaw": "Winner Match 76",
    "awayRaw": "Winner Match 78",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Winner Match 76 vs Winner Match 78, MetLife Stadium, East Rutherford"
  },
  {
    "id": "m092",
    "matchNumber": 92,
    "slug": "092-winner-match-79-vs-winner-match-80",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 5, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 79",
    "away": "Ganador Partido 80",
    "homeRaw": "Winner Match 79",
    "awayRaw": "Winner Match 80",
    "venue": "Estadio Azteca, Mexico City",
    "sourceNote": "Winner Match 79 vs Winner Match 80, Estadio Azteca, Mexico City"
  },
  {
    "id": "m093",
    "matchNumber": 93,
    "slug": "093-winner-match-83-vs-winner-match-84",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 6, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 83",
    "away": "Ganador Partido 84",
    "homeRaw": "Winner Match 83",
    "awayRaw": "Winner Match 84",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Winner Match 83 vs Winner Match 84, AT&T Stadium, Arlington"
  },
  {
    "id": "m094",
    "matchNumber": 94,
    "slug": "094-winner-match-81-vs-winner-match-82",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 6, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 81",
    "away": "Ganador Partido 82",
    "homeRaw": "Winner Match 81",
    "awayRaw": "Winner Match 82",
    "venue": "Lumen Field, Seattle",
    "sourceNote": "Winner Match 81 vs Winner Match 82, Lumen Field, Seattle"
  },
  {
    "id": "m095",
    "matchNumber": 95,
    "slug": "095-winner-match-86-vs-winner-match-88",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 7, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 86",
    "away": "Ganador Partido 88",
    "homeRaw": "Winner Match 86",
    "awayRaw": "Winner Match 88",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Winner Match 86 vs Winner Match 88, Mercedes-Benz Stadium, Atlanta"
  },
  {
    "id": "m096",
    "matchNumber": 96,
    "slug": "096-winner-match-85-vs-winner-match-87",
    "phase": "Round of 16",
    "phaseEs": "Octavos de final",
    "group": null,
    "dateLabel": "July 7, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 85",
    "away": "Ganador Partido 87",
    "homeRaw": "Winner Match 85",
    "awayRaw": "Winner Match 87",
    "venue": "BC Place, Vancouver",
    "sourceNote": "Winner Match 85 vs Winner Match 87, BC Place, Vancouver"
  },
  {
    "id": "m097",
    "matchNumber": 97,
    "slug": "097-winner-match-89-vs-winner-match-90",
    "phase": "Quarter-finals",
    "phaseEs": "Cuartos de final",
    "group": null,
    "dateLabel": "July 9, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 89",
    "away": "Ganador Partido 90",
    "homeRaw": "Winner Match 89",
    "awayRaw": "Winner Match 90",
    "venue": "Gillette Stadium, Foxborough",
    "sourceNote": "Winner Match 89 vs Winner Match 90, Gillette Stadium, Foxborough"
  },
  {
    "id": "m098",
    "matchNumber": 98,
    "slug": "098-winner-match-93-vs-winner-match-94",
    "phase": "Quarter-finals",
    "phaseEs": "Cuartos de final",
    "group": null,
    "dateLabel": "July 10, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 93",
    "away": "Ganador Partido 94",
    "homeRaw": "Winner Match 93",
    "awayRaw": "Winner Match 94",
    "venue": "SoFi Stadium, Inglewood",
    "sourceNote": "Winner Match 93 vs Winner Match 94, SoFi Stadium, Inglewood"
  },
  {
    "id": "m099",
    "matchNumber": 99,
    "slug": "099-winner-match-91-vs-winner-match-92",
    "phase": "Quarter-finals",
    "phaseEs": "Cuartos de final",
    "group": null,
    "dateLabel": "July 11, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 91",
    "away": "Ganador Partido 92",
    "homeRaw": "Winner Match 91",
    "awayRaw": "Winner Match 92",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Winner Match 91 vs Winner Match 92, Hard Rock Stadium, Miami Gardens"
  },
  {
    "id": "m100",
    "matchNumber": 100,
    "slug": "100-winner-match-95-vs-winner-match-96",
    "phase": "Quarter-finals",
    "phaseEs": "Cuartos de final",
    "group": null,
    "dateLabel": "July 11, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 95",
    "away": "Ganador Partido 96",
    "homeRaw": "Winner Match 95",
    "awayRaw": "Winner Match 96",
    "venue": "Arrowhead Stadium, Kansas City",
    "sourceNote": "Winner Match 95 vs Winner Match 96, Arrowhead Stadium, Kansas City"
  },
  {
    "id": "m101",
    "matchNumber": 101,
    "slug": "101-winner-match-97-vs-winner-match-98",
    "phase": "Semi-finals",
    "phaseEs": "Semifinales",
    "group": null,
    "dateLabel": "July 14, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 97",
    "away": "Ganador Partido 98",
    "homeRaw": "Winner Match 97",
    "awayRaw": "Winner Match 98",
    "venue": "AT&T Stadium, Arlington",
    "sourceNote": "Winner Match 97 vs Winner Match 98, AT&T Stadium, Arlington"
  },
  {
    "id": "m102",
    "matchNumber": 102,
    "slug": "102-winner-match-99-vs-winner-match-100",
    "phase": "Semi-finals",
    "phaseEs": "Semifinales",
    "group": null,
    "dateLabel": "July 15, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 99",
    "away": "Ganador Partido 100",
    "homeRaw": "Winner Match 99",
    "awayRaw": "Winner Match 100",
    "venue": "Mercedes-Benz Stadium, Atlanta",
    "sourceNote": "Winner Match 99 vs Winner Match 100, Mercedes-Benz Stadium, Atlanta"
  },
  {
    "id": "m103",
    "matchNumber": 103,
    "slug": "103-loser-match-101-vs-loser-match-102",
    "phase": "Third-place play-off",
    "phaseEs": "Tercer lugar",
    "group": null,
    "dateLabel": "July 18, 2026",
    "kickoffUtc": null,
    "home": "Perdedor Partido 101",
    "away": "Perdedor Partido 102",
    "homeRaw": "Loser Match 101",
    "awayRaw": "Loser Match 102",
    "venue": "Hard Rock Stadium, Miami Gardens",
    "sourceNote": "Loser Match 101 vs Loser Match 102, Hard Rock Stadium, Miami Gardens"
  },
  {
    "id": "m104",
    "matchNumber": 104,
    "slug": "104-winner-match-101-vs-winner-match-102",
    "phase": "Final",
    "phaseEs": "Final",
    "group": null,
    "dateLabel": "July 19, 2026",
    "kickoffUtc": null,
    "home": "Ganador Partido 101",
    "away": "Ganador Partido 102",
    "homeRaw": "Winner Match 101",
    "awayRaw": "Winner Match 102",
    "venue": "MetLife Stadium, East Rutherford",
    "sourceNote": "Winner Match 101 vs Winner Match 102, MetLife Stadium, East Rutherford"
  }
];

export function getMundialMatch(slugOrId: string): MundialMatch | undefined {
  return MUNDIAL_MATCHES.find((match) => match.slug === slugOrId || match.id === slugOrId);
}

export function getUpcomingMundialMatches(limit = 8, now = new Date()): MundialMatch[] {
  const nowMs = now.getTime();
  return MUNDIAL_MATCHES
    .filter((match) => !match.kickoffUtc || new Date(match.kickoffUtc).getTime() >= nowMs - 2 * 60 * 60 * 1000)
    .slice(0, limit);
}

export function getMatchesByDate(): Array<{ dateLabel: string; matches: MundialMatch[] }> {
  const buckets = new Map<string, MundialMatch[]>();
  for (const match of MUNDIAL_MATCHES) {
    const list = buckets.get(match.dateLabel) || [];
    list.push(match);
    buckets.set(match.dateLabel, list);
  }
  return Array.from(buckets.entries()).map(([dateLabel, matches]) => ({ dateLabel, matches }));
}

export function getMatchesByPhase(): Array<{ phase: string; phaseEs: string; matches: MundialMatch[] }> {
  const buckets = new Map<string, MundialMatch[]>();
  for (const match of MUNDIAL_MATCHES) {
    const list = buckets.get(match.phase) || [];
    list.push(match);
    buckets.set(match.phase, list);
  }
  return Array.from(buckets.entries()).map(([phase, matches]) => ({ phase, phaseEs: matches[0]?.phaseEs || phase, matches }));
}

export function formatCostaRicaDateTime(iso: string | null): string {
  if (!iso) return 'Horario por confirmar';
  return new Intl.DateTimeFormat('es-CR', {
    weekday: 'short', day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit', hour12: true,
    timeZone: 'America/Costa_Rica',
  }).format(new Date(iso));
}
